### ISSUE TITLE
Using cellbender with scCDC?

### ISSUE THREAD

**Issue by yimwy** [ZJU-UoE-CCW-LAB/scCDC#5]
Hi, I have a quick question. I am wondering if it is rationale to perform empty droplet based methods such as cellbender, then further perform decontamination using scCDC after clustering?

**Comment by ChaochenWang** [comment]
We recommend to perform DecontX and then scCDC. We have not tested combining cellbender and scCDC.

发件人: ***@***.*** ***@***.***> 代表 yimwy
发送时间: 2024年5月31日 12:57
收件人: ZJU-UoE-CCW-LAB/scCDC ***@***.***>
抄送: Subscribed ***@***.***>
主题: [SPAM] [ZJU-UoE-CCW-LAB/scCDC] Using cellbender with scCDC? (Issue #5)

 

Hi, I have a quick question. I am wondering if it is rationale to perform empty droplet based methods such as cellbender, then further perform decontamination using scCDC after clustering?

**Comment by wuliRothschild** [comment]
Hello, I wonder if this step of scCDC decontamination should be performed after filtering low-quality cells and removing doublets or before?

**Comment by ChaochenWang** [comment]
Yes. It is suggested to perform scCDC after these quality control steps.

 

发件人: ***@***.*** ***@***.***> 代表 wuliRothschild
发送时间: 2024年8月27日 18:30
收件人: ZJU-UoE-CCW-LAB/scCDC ***@***.***>
抄送: ChaochenWang ***@***.***>; Comment ***@***.***>
主题: Re: [ZJU-UoE-CCW-LAB/scCDC] Using cellbender with scCDC? (Issue #5)

 

Hello, I wonder if this step of scCDC decontamination should be performed after filtering low-quality cells and removing doublets or before?
