### ISSUE TITLE
SCT

### ISSUE THREAD

**Issue by snglcl** [ZJU-UoE-CCW-LAB/scCDC#6]
Hello, thanks for this tool. I was wondering if the contamination correction will still work if we normalized with SCTransform v2 instead of log norm/scale?

**Comment by Stephen1202-Wang** [comment]
Hi, Thank you for using our tools.

scCDC defines eGCG-/+ clusters based on normalized data and the default normalization method is log1pCP10k. If I understand correctly, the normalization method in SCTransform is log1p(counts). scCDC should be robust to various normalization methods, including SCTransform, but we have not yet validated these alternatives. It would be OK to use SCTransform but if there's no specific reason to do so, we recommend sticking with log1pCP10k for optimal results.
