### ISSUE TITLE
"counts"槽名不存在于"Assay5"类别对象中

### ISSUE THREAD

**Issue by cxlcoc** [ZJU-UoE-CCW-LAB/scCDC#7]
Error in ContaminationCorrection(nall, rownames(GCGs)) : 
  "counts"槽名不存在于"Assay5"类别对象中

**Comment by cxlcoc** [comment]
ContaminationCorrection函数中有一行“object@assays[[DefaultAssay(object)]]@data <- object@assays[[DefaultAssay(object)]]@counts”，这一行无法运行，因为我的seurat对象中data以及count应为“object@assays[[DefaultAssay(object)]]$data"和”object@assays[[DefaultAssay(object)]]$counts”,但我无法修改函数的代码

**Comment by Stephen1202-Wang** [comment]
Hi @cxlcoc ,
Thank you for using scCDC. We've developed this version of scCDC to be compatible with Seurat V4, and we've noticed some functions might not work as expected with the newly released Seurat V5. From the log file and the details you've provided, it seems the issue could be related to the version of Seurat you're using. Could you please confirm which version of Seurat you are using?

Thank you!

**Comment by cxlcoc** [comment]
Seurat V5

**Comment by Stephen1202-Wang** [comment]
Hi @cxlcoc，
The current version of scCDC was developed based on Seurat V4, and some functions may not be compatible with Seurat V5. We are working on updating scCDC to be compatible with Seurat V5, but this may take some time. In the meantime, could you try using Seurat V4 for your analysis? You can download Seurat V4 using the following link:
if (!require("remotes", quietly = TRUE)){
    install.packages("remotes")
}

library(remotes)
remotes::install_github("satijalab/seurat", ref="release/4.3.0")
